feat: es6 + visual mods
dec0dOS/zero-ui pull request #170
Opened 2023-10-06 20:14 UTC by aruznieto

## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [x] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

Issue Number: #73

## What is the new behavior?

ES6

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

I update the margin of the page to

2023-10-06 21:57 UTC, dec0dOS commented
Thanks a lot for your PR, @aruznieto!
Please check my code review.

2023-10-08 08:21 UTC, aruznieto commented
> Thanks a lot for your PR, @aruznieto! Please check my code review.

Where is it?

2023-10-08 13:45 UTC, dec0dOS requested changes

2023-10-08 13:45 UTC, dec0dOS commented on backend/routes/network.js
> -router.get("/", auth.isAuthorized, async function (req, res) {
I would prefer to import the whole module and refer to `isAuthorized()` as `auth.isAuthorized`. Thanks!
So as in other places

2023-10-08 13:45 UTC, dec0dOS commented on backend/routes/member.js
> +  deleteMemberAdditionalData(nwid, mid);
I would prefer to import the whole module and refer to `deleteMemberAdditionalData()` as `member.deleteMemberAdditionalData`. Thanks!
So as in other places

2023-10-08 13:46 UTC, dec0dOS commented
Apologies for the oversight, it appears I forgot to hit the "Finish" button on the code review page. Unfinished code reviews aren't visible to others.

2023-10-08 14:37 UTC, aruznieto commented
> Apologies for the oversight, it appears I forgot to hit the "Finish" button on the code review page. Unfinished code reviews aren't visible to others.

Pushed, can you add dev: commit?

2023-10-08 15:24 UTC, dec0dOS requested changes
Seems like you have added the `package-lock.json` by mistake. Please delete it from the root. You should also remove croner from the root `package.json` file

2023-10-08 15:27 UTC, aruznieto commented
> Seems like you have added the `package-lock.json` by mistake. Please delete it from the root. You should also remove croner from the root `package.json` file

Done. Sorry

2023-10-08 15:29 UTC, dec0dOS commented
Everything else seems fine! Looks good to me. Have you had a chance to test the croner package to make sure it behaves exactly as expected?

Keep in mind that `node-cron` and `croner` are implemented quite differently under the hood

2023-10-08 15:34 UTC, dec0dOS commented
Hmm, it looks like the developer is trying to provide an easy drop-in replacement alternative for node-cron: https://croner.56k.guru/migration/#switching-from-node-cron

Everything should be fine

2023-10-08 15:36 UTC, aruznieto commented
> Hmm, it looks like the developer is trying to provide an easy drop-in replacement alternative for node-cron

Yes

2023-10-08 15:41 UTC, merged

2023-10-08 15:42 UTC, dec0dOS commented
Thank you for collaborating, @aruznieto!