feat: i18n
dec0dOS/zero-ui pull request #182
Opened 2023-10-16 15:37 UTC by aruznieto

Add i18n capability.

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: #137

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Actually I trying to add the possibility to change the language.

2023-10-16 17:04 UTC, dec0dOS commented on backend/routes/auth.js
> +    error: "tooManyAttemps",
I don't think we should introduce i18n on the backend side. That is not considered best practice. Please retain verbose error messages on the backend side.

2023-10-16 19:50 UTC, aruznieto commented on backend/routes/auth.js
> +    error: "tooManyAttemps",
And how do you translate this sentences?

2023-10-17 00:05 UTC, dec0dOS commented on backend/routes/auth.js
> +    error: "tooManyAttemps",
My apologies, I mistakenly believed that this message wouldn't be passed to the frontend

2023-10-17 16:07 UTC, aruznieto commented
Added settings page (no tested on a computer with a different than Spanish or English)

2023-10-17 18:27 UTC, aruznieto commented
https://crowdin.com/project/zero-ui

2023-10-19 05:56 UTC, dec0dOS requested changes

2023-10-19 05:56 UTC, dec0dOS commented on frontend/public/locales/en/common.json
> +  "network_one": "Network",
Please don't mix camelCase and snake_case

2023-10-19 05:56 UTC, dec0dOS commented on frontend/public/locales/en/common.json
> +  "netId": "Network ID",
I would prefer to have more readable variable names. netId -> networkId

2023-10-19 05:56 UTC, dec0dOS commented on frontend/public/locales/en/common.json
> +  "tooManyAttemps": "Too many login attempts, please try again in 15 minutes.",
"Attempts" typo

2023-10-19 05:56 UTC, dec0dOS commented on frontend/public/locales/en/common.json
> +  "enaBroadcast": "Enable Broadcast",
enableBroadcast

2023-10-19 05:56 UTC, dec0dOS commented on frontend/src/components/HomeLoggedIn/HomeLoggedIn.jsx
> +            {networks[0] && String(networks[0]["id"]).slice(0, 10)}
Is that really necessary to wrap `networks[0]["id"]` with String object? Seems like not the best practice.

2023-10-19 05:56 UTC, dec0dOS commented on frontend/src/components/LogIn/LogIn.jsx
> +      &nbsp;
It is better to use elements from Material UI for spacing

2023-10-19 05:56 UTC, dec0dOS commented on frontend/src/components/NetworkMembers/components/AddMember/AddMember.jsx
> +      <Typography>{t("addMemberMan")}</Typography>
The name `addMemberMan` can be quite confusing for a variable. It might be better to simply copy the keys from any .json translation file and check if it's easy to reproduce the same result using those keys. In this way, the key names should be descriptive enough for better understanding

2023-10-19 05:56 UTC, dec0dOS commented on frontend/src/components/SettingsComponent/SettingsComponent.jsx
> +export default SettingsComponent;
The component's name is a bit confusing. It's best to avoid including the word "Component" in the component's name.

2023-10-19 05:56 UTC, dec0dOS commented on frontend/src/i18n.js
> +    //lng: "en",
It's better to remove dev comments before merging

2023-10-19 05:56 UTC, dec0dOS commented on frontend/src/components/SettingsComponent/SettingsComponent.jsx
> +  Checkbox,
Some variables here are unused

2023-10-19 05:56 UTC, dec0dOS commented on frontend/src/components/SettingsComponent/SettingsComponent.jsx
> +import API from "utils/API";
There are some unused imports in this code

2023-10-19 05:56 UTC, dec0dOS commented on frontend/src/routes/Settings/Settings.jsx
> +            You are not authorized. Please Log In
There is no translation provided here

2023-10-19 05:56 UTC, dec0dOS commented
> https://crowdin.com/project/zero-ui
> 
> We can talk on Discord/Telegram if u want

I would like to know more about the crowdin platform. Please share your contacts.

2023-10-19 05:59 UTC, aruznieto commented on frontend/public/locales/en/common.json
> +  "network_one": "Network",
This is because i18n use _ to "modify" words (create plurals for example)

2023-10-19 06:00 UTC, dec0dOS commented
> Added settings page (no tested on a computer with a different than Spanish or English). Maybe you should consider to remove all console.logs on all platform or enable it only on debug mode, nor production

Removing the console.log statements from the frontend doesn't offer any significant benefits. ZeroUI is primarily used by administrators, not average users. Logs can be quite helpful in identifying and resolving issues, so removing them doesn't really contribute to the improvement of the platform in any way

2023-10-19 06:01 UTC, aruznieto commented
> > https://crowdin.com/project/zero-ui
> 
> > 
> 
> > We can talk on Discord/Telegram if u want
> 
> 
> 
> I would like to know more about the crowdin platform. Please share your contacts.
> 
> 

Same username that here. @aruznieto (tg)

2023-10-19 06:06 UTC, dec0dOS commented
> Same username that here. @aruznieto (tg)

Right now, I'm a bit tied up, but I'll reach out to you later

2023-10-19 12:26 UTC, dec0dOS requested changes
Some files are still missing the proper translation. Check the https://github.com/aruznieto/zero-ui/blob/i18n/frontend/src/components/NetworkSettings/components/ManagedRoutes/ManagedRoutes.jsx

2023-10-19 12:26 UTC, dec0dOS commented on frontend/public/locales/en/common.json
> +  "ips": "Managed IPs",
`managedIPs` is better

2023-10-19 12:26 UTC, dec0dOS commented on frontend/public/locales/en/common.json
> +  "status": "Last seen",
`lastSeen`?

2023-10-19 13:01 UTC, dec0dOS requested changes
![Screenshot 2023-10-19 at 13 58 59](https://github.com/dec0dOS/zero-ui/assets/14824142/5da08ab9-8527-41af-a53e-416d383a599f)
![Screenshot 2023-10-19 at 13 59 03](https://github.com/dec0dOS/zero-ui/assets/14824142/0bd1e8e3-9c4a-469e-9157-fd29041fcba0)
![Screenshot 2023-10-19 at 13 59 11](https://github.com/dec0dOS/zero-ui/assets/14824142/993c2883-15e7-42d1-a1be-d9137776a96c)
![Screenshot 2023-10-19 at 13 59 28](https://github.com/dec0dOS/zero-ui/assets/14824142/8a776fc5-3d53-4bba-a745-e4cd90dc850f)
![Screenshot 2023-10-19 at 13 59 19](https://github.com/dec0dOS/zero-ui/assets/14824142/b02a77b1-7770-4f02-9b48-ddd6a226854c)

2023-10-19 13:02 UTC, dec0dOS commented
![Screenshot 2023-10-19 at 14 01 56](https://github.com/dec0dOS/zero-ui/assets/14824142/cfe2ad6c-ff8b-4140-887d-c5eb9766b3ad)

2023-10-19 13:15 UTC, aruznieto commented
I think now all is done.

2023-10-19 18:51 UTC, dec0dOS commented
LGTM

2023-10-19 18:52 UTC, merged